spring:
  r2dbc:
    url: 'r2dbc:h2:file:///./target/thymeleaf-dynamic-htmx-database'
    username: 'sa'
    password: ''
    properties:
      Mode: MySQL
      AUTO_SERVER: TRUE
      AUTO_RECONNECT: TRUE
      MULTI_THREADED: TRUE
      DB_CLOSE_ON_EXIT: TRUE
  liquibase:
    change-log: classpath*:/liquibase/changelog-master.xml
logging:
  level:
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
