name: CI
on:
  push:
  #pull_request:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to trigger manual jobs
        required: false
        default: ''
jobs:
  tests:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 20 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: java-cache
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: sudo apt-get install -y httpie
      - run: sudo rm -rfv ~/.m2/repository/io/github/daggerok
      - run: cd $GITHUB_WORKSPACE ; ./mvnw clean compile spring-boot:start
      - run: |
          http --ignore-stdin         get :8080            ;
          http --ignore-stdin --form post :8080 name=Hello ;
          http --ignore-stdin         get :8080            ;
      - run: cd $GITHUB_WORKSPACE ; ./mvnw spring-boot:stop
